name: Bug report
description: Report a problem with Fedora Plasma Glow Kit
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste relevant non-private logs.
      render: shell
