#!/usr/bin/env bash

# Waits for and returns the first message generated by a given service, interface path method

BUS_TYPE=${1}
SERVICE=${2}
INTERFACE=${3}
DBUS_PATH=${4}
METHOD=${5}
exit_code=130

while IFS= read -r line; do
  if [[ "$line" == *"${INTERFACE}.${METHOD}"* ]] && [[ "$line" == *"${DBUS_PATH}"* ]]; then
    echo "$line"
    exit_code=0
    break
  fi
  if [[ "$line" == *"Error"* ]]; then
    exit_code=1
    break
  fi
done < <(gdbus monitor --"${BUS_TYPE}" --dest "${SERVICE}" 2>&1)

exit "$exit_code"
